language: node_js
node_js:
- 5.1.0
branches:
  only:
  - release
env:
  global:
  - secure: S8tgKYowj7XFxd/RyW5WYry3E8uLdrZnKFB04P7Wq7LB6EJugay+WD/42ke2MODnBQAD0gctPKWCB50aEe7brm+GJPIlHOi1EYoJMxUR0mY7z/oEBi9hD8LeaUfJtoMz8X7R/QbXvgmWg3uTfBBb4UuLM5SVzj6XLLff/KC1iFtAMk3zFy0Wl1RHemIsH86/q8JyfIcXX1kRw5U2FfCVJEBv9ZYk/MXsaE+PLaTUcaOTm1xk1Wawdt8m6ykDjo8uN/i+fTTsJR9SOcskEP5nvf68h7WPXM6daPnRIanfiO+dJRsbEg4Zlaz6d+Pu/CzFNkBLvUZUVq14aDPgLNXg/+Pr71VXR63zOiwKG4r9Ek3PUrDz6OfD3heWgzBMWMzeyD7adddlNDMGPD/6umSy3M7EkuiaC5QojnkoPgRrwg0v4dheZIQs9Bo9fKfAwacaKQYCdkayB5LDXv4pinbbj6rHfFYQJlwzawqqNxCqllwOdONzdCli30K62zWrUn1L50rCV8cUPgRb2dle2yH+tHKydlol2FTZTeYkAmSmoNY8ngvp5R9w693wEKEMB0HwH5BHU8n47y0G0cZ+liX30TnVHtCdSmj4E3kDv9EEvERgqzf66s/5Mv7M80ScdWC6lb26ZCoc1SQl4Vz8kTVeg4aI/RXMBhE1QIpFtQ3v+Mg=
  - secure: ISqDdPXjSX00SiIBps0BCoAHSoEQv9iJt96Gq+pxf14O4kdZH3r/9CkevJRt1+xcwQKGMdyK+1noieIA+zxA+KHunM4W8KxwNGvuxjLJu9UhPUKnaQ9P0PtrUrSgfXw7Sh2NwFVxQxgvZIAnQmJ2tMvA7lekC4KlUCHlWQjrg97HzR9Ru17pqj2cxxSK1MTvlUMho7/3MUlHSSup+2sXRB6MYgMRVsrCLEQWf0YJEVxE49aC/nH9SFXw0jAVlCOsmwHrtkAKdhhyAOXMrcgkq5R9PniKr8Xx+UD/OiZLpTWbC4PKUNHwngxW85LWHT0ZUrvk42Qk4SfRY+CAYLGkEZk+ay53g0PwJLDakxsY2FxBZ3Zg6bwfCweFzQ4z6qqfxBvQW8RQvCY707xdHBwH5iAmYriMrnRQzrpTaGdyXnpYIW8PGFcnZgrobiTxMxUGIARbC/9zookcI1d/LC+d+MNsv1HMlf7ezu61rSaHJOGBIIoJOEzBn7hx24ZZl2e6ApYSW9N6KQEDDh4aJYCxxtVmZCp1uqU7N9dwfoi/6NtmqUhXQsGY+SdKhvMkRUtd/KpYhk9NNStINqn3mw6GeJmPJJ8n+5yOP6K+8Zqee5yRpWJIEzKP6KEMzYq2WDxDNfHway6amuw1ilTC7cH8lAs+JCgYr1ViKS2GRe59PEA=
script: npm run build
after_success:
- rsync --delete --omit-dir-times -av dist/ rsync://$DEPLOY_USER@nicholasbeach.com/html
